library(XML)
library(RCurl)
fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml"
xData <- getURL(fileURL)
doc <- xmlTreeParse(xData, useInternalNodes = TRUE)
rootNode <- xmlRoot(doc)
zips <- xpathSApply(rootNode, "//zipcode", xmlValue)
zips <- as.vector(zips)
zips <- as.numeric(zips)
print(sum(as.numeric(zips == 21231)))
